### ISSUE TITLE
Package name: avoiding confusion with psychmeta

### ISSUE THREAD

**Issue by bwiernik** [josue-rodriguez/psychmetadata#1]
Congrats on the package! This looks like a great archive!

One thing I’m a little concerned about is potential confusion with our package “psychmeta”—eg, someone might think this is a datasets package to accompany psychmeta ala psychTools or ggplot2movies. 

I was wondering if you might consider adjusting the name to something like “psymetadata”? I know that you spent a long time thinking about names, so sorry if this is an annoying request.

**Comment by josue-rodriguez** [comment]
No problem! I will change it in the morning. I submitted to CRAN this morning so if it passes then there will be a small amount of time with the current name, but I will change it asap. Sorry about that!
