### ISSUE TITLE
Make data visible online - e.g., through pkgdown website

### ISSUE THREAD

**Issue by LukasWallrich** [josue-rodriguez/psychmetadata#2]
Thanks for this great package! It would be even more useful with an easier way to see the available data more easily - e.g., by adding a pkgdown website that shows the documentation entries in the form of a webpage? I'd be happy to submit a PR if helpful ...

**Comment by josue-rodriguez** [comment]
Hi Lukas,

Thank you for the kind words, and apologies for such a delayed response! As might be able to tell, I'm currently not actively maintaining this package 😅. If you'd like to add create a pkgdown website, I'd be more than happy to merge the PR and add you as an author to the package! But please only do so if you feel it is something you'd like to do.

All the best,
Josue

**Comment by josue-rodriguez** [comment]
The pkgdown website is now live at [https://josue-rodriguez.github.io/psymetadata/](https://josue-rodriguez.github.io/psymetadata/). Thank you for your work!
